spring:
  webflux:
    static-locations: "classpath:/static/"
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - OPTIONS
server:
  port: 3001
